CREATE TABLE [dbo].[User]
(
	[IdUser] INT NOT NULL IDENTITY,
	[FirstName] VARCHAR(64) NOT NULL,
	[LastName] VARCHAR(64) NOT NULL,
	[Email] VARCHAR(256) NOT NULL,
	[Phone] VARCHAR(16),
	[Login] VARCHAR(32) NOT NULL,
	[Password] VARBINARY(32) NOT NULL,
	[BirthDate] DATE NOT NULL,

	CONSTRAINT PK_User PRIMARY KEY CLUSTERED ([IdUser] ASC),
	CONSTRAINT UK_User_Email UNIQUE ([Email]),
	CONSTRAINT UK_User_Login UNIQUE ([Login]),
	CONSTRAINT UK_User_Phone UNIQUE ([Phone])
)